export const createProjectPageRegistry = () => [
  {
    id: 'dashboard',
    label: 'Dashboard',
    route: '/dashboard',
    description: 'Business overview, alerts, and owner review.',
    actionTypes: ['open_page', 'operational_note'],
    keywords: ['dashboard', 'overview', 'alert', 'risk'],
  },
  {
    id: 'products',
    label: 'Products',
    route: '/products',
    description: 'Product catalog and product details.',
    actionTypes: ['review_product'],
    keywords: ['product', 'products', 'catalog', 'sku'],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    route: '/inventory',
    description: 'Stock levels and inventory operations.',
    actionTypes: ['review_stock', 'review_inventory'],
    keywords: ['stock', 'inventory', 'low stock', 'warehouse'],
  },
  {
    id: 'orders',
    label: 'Orders',
    route: '/orders',
    description: 'Orders, sales, invoices, and fulfillment.',
    actionTypes: ['review_order', 'review_invoice'],
    keywords: ['order', 'orders', 'invoice', 'sale', 'fulfillment'],
  },
  {
    id: 'customers',
    label: 'Customers',
    route: '/customers',
    description: 'Customers, clients, and follow-ups.',
    actionTypes: ['follow_up_client', 'review_customer'],
    keywords: ['client', 'customer', 'follow up', 'debt'],
  },
  {
    id: 'reports',
    label: 'Reports',
    route: '/reports',
    description: 'Reports, revenue, finance, and analytics.',
    actionTypes: ['review_report'],
    keywords: ['report', 'reports', 'revenue', 'finance', 'analytics'],
  },
  {
    id: 'settings',
    label: 'Settings',
    route: '/settings',
    description: 'Application and business settings.',
    keywords: ['settings', 'configuration'],
  },
];
