export const createArgjiraPageRegistry = () => [
  {
    id: 'dashboard',
    label: 'Dashboard',
    route: '/dashboard',
    description: 'Business overview, current alerts, daily status, and owner review.',
    actionTypes: ['open_page', 'operational_note'],
    keywords: ['dashboard', 'overview', 'alert', 'risk', 'today', 'owner'],
  },
  {
    id: 'pos',
    label: 'POS / Shitje',
    route: '/pos',
    description: 'Point-of-sale and retail sales workflow.',
    actionTypes: ['open_page'],
    keywords: ['pos', 'sale', 'retail', 'cash', 'card'],
  },
  {
    id: 'outgoing_invoices',
    label: 'Fatura',
    route: '/invoices/dalese',
    description: 'Outgoing customer invoices, unpaid invoices, payments, and sales documents.',
    aliases: ['invoices', 'invoice', 'fatura', 'dalese', 'unpaid invoices'],
    legacyRoutes: ['/invoices'],
    actionTypes: ['review_invoice'],
    keywords: ['invoice', 'invoices', 'unpaid', 'debt', 'customer debt', 'payment', 'fatura'],
  },
  {
    id: 'delivery_notes',
    label: 'Flete Dergese',
    route: '/invoices/flete-dergese',
    description: 'Delivery notes and outgoing delivery documents.',
    aliases: ['flete dergese', 'delivery notes'],
    keywords: ['delivery', 'shipment', 'flete dergese'],
  },
  {
    id: 'incoming_invoices',
    label: 'Flete Pranim',
    route: '/invoices/hyrese',
    description: 'Incoming invoice and acceptance documents.',
    aliases: ['hyrese', 'flete pranim', 'incoming invoices'],
    keywords: ['incoming', 'supplier invoice', 'flete pranim', 'hyrese'],
  },
  {
    id: 'processing_invoices',
    label: 'Fatura Perpunime',
    route: '/invoices/processing',
    description: 'Gold processing invoices and processing operations.',
    aliases: ['processing', 'perpunime'],
    legacyRoutes: ['/processing'],
    keywords: ['processing', 'perpunime', 'workshop'],
  },
  {
    id: 'gold_melting',
    label: 'Shkrirje Ari',
    route: '/invoices/shkrirje-ari',
    description: 'Gold melting documents and operations.',
    aliases: ['shkrirje ari', 'gold melting'],
    keywords: ['melting', 'shkrirje', 'gold melting'],
  },
  {
    id: 'purchases',
    label: 'Blerje Ari',
    route: '/purchase',
    description: 'Gold purchases and purchase records.',
    aliases: ['purchase', 'purchases', 'blerje ari', 'ari skrap'],
    actionTypes: ['review_purchase'],
    keywords: ['purchase', 'purchases', 'supplier', 'scrap gold', 'blerje'],
  },
  {
    id: 'clients',
    label: 'Klientet',
    route: '/clients',
    description: 'Clients, follow-ups, customer details, and client balances.',
    aliases: ['clients', 'client', 'customers', 'klientet'],
    actionTypes: ['follow_up_client', 'review_record'],
    keywords: ['client', 'customer', 'follow up', 'balance', 'klient'],
  },
  {
    id: 'stock_main',
    label: 'Magacin 1',
    route: '/stock',
    description: 'Main warehouse stock and inventory.',
    aliases: ['stock', 'inventory', 'magacin 1', 'warehouse 1'],
    actionTypes: ['review_stock', 'update_product_price', 'bulk_update_product_prices', 'bulk_update_product_prices_by_category', 'update_product_details', 'bulk_update_product_details', 'bulk_update_product_details_by_category'],
    keywords: ['stock', 'inventory', 'warehouse', 'magacin', 'low stock'],
  },
  {
    id: 'stock_secondary',
    label: 'Magacin 2',
    route: '/stock-1',
    description: 'Second warehouse stock and inventory.',
    aliases: ['stock 2', 'inventory 2', 'magacin 2', 'warehouse 2'],
    actionTypes: ['update_product_price', 'bulk_update_product_prices', 'bulk_update_product_prices_by_category', 'update_product_details', 'bulk_update_product_details', 'bulk_update_product_details_by_category'],
    keywords: ['stock 2', 'warehouse 2', 'magacin 2'],
  },
  {
    id: 'reports',
    label: 'Raportet',
    route: '/reports',
    description: 'Revenue, finance, debts, purchases, stock, and business reports.',
    aliases: ['reports', 'report', 'raportet', 'finance'],
    actionTypes: ['review_report'],
    keywords: ['report', 'reports', 'finance', 'revenue', 'profit', 'debt', 'analytics'],
  },
  {
    id: 'monitoring',
    label: 'Monitorim',
    route: '/monitoring',
    description: 'System monitoring and audit-style operational logs.',
    aliases: ['monitoring', 'monitorim'],
    keywords: ['monitoring', 'audit', 'logs'],
  },
  {
    id: 'settings',
    label: 'Cilesimet',
    route: '/settings',
    description: 'Company settings, invoice settings, and configuration.',
    aliases: ['settings', 'cilesimet', 'configuration'],
    keywords: ['settings', 'configuration', 'company settings'],
  },
];
